import dynamic from "next/dynamic";
import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

const TopGlobalNavbar = dynamic(
  () => import("./components/blocks/TopGlobalNavbar/TopGlobalNavbar"),
  { ssr: false }
);
const MainGlobalNavbar = dynamic(
  () => import("./components/blocks/MainGlobalNavbar/MainGlobalNavbar"),
  { ssr: false }
);
const PageStyle = dynamic(() => import("./components/ui/PageStyle/PageStyle"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Crypto App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={spaceGrotesk.className}>
          <TopGlobalNavbar />
          <MainGlobalNavbar />
          <PageStyle>{children}</PageStyle>
        </body>
      </StoreProvider>
    </html>
  );
}
