import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import { Space_Grotesk } from "next/font/google";
import PageStyle from "./components/ui/PageStyle/PageStyle";
import TopGlobalNavbar from "./components/blocks/TopGlobalNavbar/TopGlobalNavbar";
import MainGlobalNavbar from "./components/blocks/MainGlobalNavbar/MainGlobalNavbar";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={spaceGrotesk.className}>
          <TopGlobalNavbar />
          <MainGlobalNavbar />
          <PageStyle>{children}</PageStyle>
        </body>
      </StoreProvider>
    </html>
  );
}
